# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aec494e19e232f7afcba574365f35c8bc9f3a4335be291874d4349f4430bfee6071c5b590af99146a35718349ca5a37247b1b9e1af8bffc91615f954e0121ed5

test:
  secret_key_base: d20fcf2beaddd2bbf599743b71976ecede30834d221a07d0f9e425791c2601697f5aae68b35e6d006e8d3a497519e7307b8b821af7c0f3a5d41abce5f83040ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
